version: '3.6'
services:
  frontend:
    build: web
    ports:
      - "4200:4200"
    container_name: web-container
    links:
      - backend
    restart: always
  backend:
    build: api
    ports:
      - "3000:3000"
    container_name: api-container
    links:
      - db
    restart: always
  db:
    image: mysql:5.7
    command: --disable-partition-engine-check
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=MFuser
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=MFabrik
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
